import { Listing } from "./types";

export const listing: Listing = {
  id: "1",
  title: "Romantic Jacuzzi 1BHK Candolim | Mirashya UG10",
  photoCount: 26,
  propertyType: "Entire serviced apartment",
  location: "Candolim, India",
  guests: 3,
  bedrooms: 1,
  beds: 1,
  bathrooms: 1,
  isGuestFavourite: true,
  rating: 4.95,
  reviewCount: 19,
  hostName: "Mirashya Homes",
  hostYearsHosting: 2,
  highlights: [
    {
      icon: "waves",
      title: "Outdoor entertainment",
      description: "The pool and alfresco dining are great for summer trips.",
    },
    {
      icon: "fan",
      title: "Designed for staying cool",
      description: "Beat the heat with the A/C and ceiling fan.",
    },
    {
      icon: "door-open",
      title: "Self check-in",
      description: "You can check in with the building staff.",
    },
  ],
  description:
    "🌴 Plan Your Relaxing Holiday at Amor De Goa by Mirashya Homes! ✨ Stay in this cozy 1BHK in the heart of Candolim, featuring a private jacuzzi 🛁 for the perfect unwind. Enjoy high-speed WiFi 💻, Smart TV 📺, pet-friendly comfort 🐾, and stylish interiors. Just minutes from Candolim Beach 🏖️, popular cafés, restaurants, and nightlife 🍹, it's the ideal base for your Goa getaway.",
  rooms: [
    { name: "Bedroom", bedInfo: "1 double bed", photoNumber: 6 },
    { name: "Living room", bedInfo: "1 sofa", photoNumber: 7 },
  ],
  amenities: [
    { icon: "utensils", label: "Kitchen", available: true },
    { icon: "wifi", label: "Wifi", available: true },
    { icon: "briefcase", label: "Dedicated workspace", available: true },
    { icon: "car", label: "Free parking on premises", available: true },
    { icon: "waves", label: "Pool", available: true },
    { icon: "bath", label: "Hot tub", available: true },
    { icon: "paw-print", label: "Pets allowed", available: true },
    { icon: "camera", label: "Exterior security cameras on property", available: true },
    { icon: "shield-alert", label: "Carbon monoxide alarm", available: false },
    { icon: "flame", label: "Smoke alarm", available: false },
  ],
  totalAmenityCount: 50,
  pricePerStay: 28499,
  currency: "₹",
  nights: 5,
  checkIn: "10/18/2026",
  checkOut: "10/23/2026",
  dateRangeLabel: "18 Oct 2026 - 23 Oct 2026",
  guestsSelected: 2,
  freeCancellationDate: "17 October",
  categoryRatings: [
    { label: "Cleanliness", score: 5.0, icon: "spray-can" },
    { label: "Accuracy", score: 5.0, icon: "circle-check" },
    { label: "Check-in", score: 5.0, icon: "search" },
    { label: "Communication", score: 5.0, icon: "message-circle" },
    { label: "Location", score: 4.8, icon: "map" },
    { label: "Value", score: 4.8, icon: "tag" },
  ],
  ratingBars: [
    { stars: 5, percent: 92 },
    { stars: 4, percent: 8 },
    { stars: 3, percent: 0 },
    { stars: 2, percent: 0 },
    { stars: 1, percent: 0 },
  ],
  highlightTags: [
    { icon: "bed-double", label: "Comfort", count: 6 },
    { icon: "circle-check", label: "Accuracy", count: 5 },
    { icon: "bath", label: "Hot tub", count: 5 },
    { icon: "gift", label: "Condition", count: 4 },
    { icon: "gift", label: "Hospitality", count: 8 },
    { icon: "sparkles", label: "Cleanliness", count: 4 },
    { icon: "image", label: "Amenities", count: 2 },
  ],
  reviews: [
    {
      id: "r1",
      name: "Amit",
      avatarInitial: "A",
      timeOnAirbnb: "2 months on Airbnb",
      rating: 5,
      date: "1 week ago",
      text: "Very helpful and responsive team. Safe and peaceful stay. loved everything about the property.",
    },
    {
      id: "r2",
      name: "Aheesh",
      avatarInitial: "A",
      timeOnAirbnb: "3 years on Airbnb",
      rating: 5,
      date: "2 weeks ago",
      text: "We had a wonderful stay. The apartment was clean, comfortable, and exactly as shown in the photos. The host was very responsive and helpful throughout our stay. We would definitely recommend this place and would love to stay here again.",
    },
    {
      id: "r3",
      name: "Samiksha",
      avatarInitial: "S",
      timeOnAirbnb: "8 months on Airbnb",
      rating: 5,
      date: "May 2026",
      text: "the host nitish was really great help",
    },
    {
      id: "r4",
      name: "Vedant",
      avatarInitial: "V",
      timeOnAirbnb: "4 years on Airbnb",
      rating: 5,
      date: "May 2026",
      text: "We had an amazing stay at this property in Goa! The entire home was spotless and exceptionally well-maintained, making us feel comfortable from the moment we arrived. The cleanliness standards were truly impressive, with every corner of the house looking fresh and pristine....",
    },
    {
      id: "r5",
      name: "Vaibhav S",
      avatarInitial: "V",
      timeOnAirbnb: "3 years on Airbnb",
      rating: 5,
      date: "May 2026",
      text: "Great great experience living out there , can't expect more , will always look for it in the future and will recommend my friends too.",
    },
    {
      id: "r6",
      name: "Mohd",
      avatarInitial: "M",
      timeOnAirbnb: "5 years on Airbnb",
      rating: 5,
      date: "May 2026",
      text: "Great place. Exactly as described in the listing.",
    },
  ],
  neighbourhood: "Candolim, Goa, India",
  neighbourhoodHighlights:
    "Located in the heart of Candolim, Amor de Goa offers a peaceful stay with easy access to beaches, cafés, and popular attractions.",
  hostRating: 4.68,
  hostReviewCount: 1463,
  hostResponseRate: "100%",
  hostResponseTime: "Responds within an hour",
  hostBornDecade: "Born in the 80s",
  hostSchool: "Where I went to school: NIZWAR GOA",
  coHosts: [
    { name: "Shivam", avatarInitial: "S" },
    { name: "Aman Dev Mishra", avatarInitial: "A" },
    { name: "Maria Karea Miyanda", avatarInitial: "M" },
    { name: "Simral", avatarInitial: "S" },
    { name: "Pallavi", avatarInitial: "P" },
    { name: "Sahyadra", avatarInitial: "S" },
    { name: "Sarat", avatarInitial: "S" },
    { name: "Amana", avatarInitial: "A" },
  ],
  cancellationPolicy:
    "Free cancellation before 17 October. Cancel before check-in on 18 October for a partial refund.",
  houseRules: [
    "Check-in after 2:00 pm",
    "Checkout before 11:00 am",
    "2 guests maximum",
  ],
  safetyItems: [
    "Carbon monoxide alarm not reported",
    "Smoke alarm not reported",
    "Exterior security cameras on property",
  ],
  nearbyStays: [
    { id: "n1", title: "Beautiful flat with a view for life", price: 42599, rating: 4.95, photoNumber: 12 },
    { id: "n2", title: "MAQNA - 1bhk with private pool", price: 142238, rating: 4.95, photoNumber: 13 },
    { id: "n3", title: "Greenhouse Luxury Flat with plunge pool, Calangute", price: 154689, rating: 4.94, photoNumber: 14 },
    { id: "n4", title: "The Tropical Studio | 5 mins to the beach", price: 152633, rating: 4.99, photoNumber: 15 },
    { id: "n5", title: "Luxury Casa Bella 1BHK with plunge pool, Calangute", price: 159802, rating: 4.94, photoNumber: 16 },
  ],
};
